#!/usr/bin/env python
# coding=utf-8

"""
ICS driven virus scanner
See included readme.md for more information.
"""

import shlex
import subprocess
import time
import kopano
import sssp
import traceback
from MAPI.Tags import *
from kopano import Config, log_exc
from thread import start_new_thread

CONFIG = {
	'run_as_user': Config.string(default="kopano"),
	'run_as_group': Config.string(default="kopano"),
	'autoremove': Config.boolean(default=False),
	'sssp_ip': Config.string(default="127.0.0.1"),
	'sssp_port': Config.integer(default=4010),
	'batch_scan_interval': Config.integer(default=24*3600), # Scan all attachments every x seconds. Default 1d
	'livescanner_enabled': Config.boolean(default=False),
	'batchscanner_enabled': Config.boolean(default=False),
	'virus_folder': Config.string(default="Cleaned"),
}

class Service(kopano.Service):
	def main(self):
		self.server = self.server
		self.state = self.server.state
		self.sssp_ip = self.config['sssp_ip']
		self.sssp_port = self.config['sssp_port']
		self.autoremove = self.config['autoremove'] # or self.options['autoremove']

		if self.autoremove:
			self.log.info("Autoremove is enabled.")
		else:
			self.log.info("Autoremove is disabled.")

		self.catcher = Checker(self)
		if self.config['livescanner_enabled']:
			self.log.info("LiveScanner enabled.")
			start_new_thread(self.livescanner, ())
		else:
			self.log.info("LiveScanner disabled.")
			
		
		if self.config['batchscanner_enabled']:
			self.log.info("BatchScanner enabled.")
			start_new_thread(self.batchscanner, ())
		else:
			self.log.info("BatchScanner disabled.")
		
		while True:
			time.sleep(24*3600)
			self.log.info("Main thread woke up. Going asleep again.")
		
	def livescanner(self):
		self.log.info ('LiveScanner: Starting.')
		while True:
			try:
				self.state = self.server.sync(self.catcher, self.state)
			except Exception as e:
				self.log.error('Error: [%s]' % e)
				time.sleep(5)
			time.sleep(1)

	def batchscanner(self):
		while True:
			self.log.info ('BatchScanner: Starting')
			for user in self.server.users():
				self.log.info ('BatchScanner: Scanning user: [%s]' % user.name)
				for folder in user.store.folders():
					self.log.info ('BatchScanner: Scanning user: [%s] folder: [%s]' % (user.name, folder.name))
					for item in folder.items():
						self.scanmail(item)
			self.log.info ('BatchScanner: Finished. Sleeping for ' + str(self.config['batch_scan_interval']) + " seconds")
			time.sleep(self.config['batch_scan_interval'])

	def scanmail(self, email):
		user = email.store.user
		virus_found = False
		for attachment in email.attachments():
			try:
				virus = self.scan_attachment(attachment)
				if virus == '': # No virus detected.
					continue
				else:
					self.log.error ('Virus found: User: %s, Folder: %s, Subject: %s, Filename: %s, Virus: %s' % (user.name, email.folder.name, email.subject, attachment.name, virus))
					virus_found = True
					try:
						if self.autoremove:
							self.delete_attachment(email, attachment, virus)
					except Exception as del_e:
						self.log.error ("Unable to remove attachment: [%s] [%s] [%s]" % (email.subject, attachment.name, del_e))
			except Exception as e:
				self.log.error("Unable to scan attachment: User: %s, Folder: %s, Subject: %s, Filename: %s, Exception: %s" % (user.name, email.folder.name, email.subject, attachment.name, e))

		if virus_found and self.autoremove:
			email.move(email.store.folder(self.config['virus_folder'], None, False, True)) # Create if it doesn't exist.


	def delete_attachment(self, email, attachment, virus):
		msg = "Attachment %s was infected with: %s" % (attachment.filename, virus)
		self.log.info ('Autoremoving attachment: [%s]' % (attachment.name))
		email.delete(attachment)
		email.create_attachment(attachment.filename + "-removed.txt", msg)
		email.subject = "[CLEANED] " + email.subject
		email.text = msg + "\n" + email.text
		
	def scan_attachment(self, attachment):
		try:
			virus_scanner = sssp.sssp(self.sssp_ip, self.sssp_port)
			if not virus_scanner.selftest():
				self.log.error("Virus scanner self-test failed. Will skip attachment %s. Sorry." % (attachment.filename))
				return ''
			result, msg = virus_scanner.check(attachment.data)
			if result:
				return ''
			else:
				virus = msg.replace('Message is infected with ', '')
				return virus
			virus_scanner.disconnect()
		except:
			self.log.error('Virus scan engine reported an error: %s. Will have to skip attachment: %s. Sorry' % (traceback.format_exc(), attachment.filename))
			return ''

class Checker(object):
	def __init__(self, service):
		self.log = service.log
		self.service = service


	def update(self, item, flags):
		if item.message_class == 'IPM.Note' and flags == 2048: # Only new mails are processed!??
			self.service.scanmail(item)

def main():
	parser = kopano.parser('ckpsF')	 # select common cmd-line options
	# parser.add_option("--autoremove", dest="autoremove", action="store_true", default=False, help="remove infected attachments")
	options, args = parser.parse_args()
	service = Service('virusd', config=CONFIG, options=options)
	service.start()



if __name__ == '__main__':
	main()
